apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: aura-api.default.svc.cluster.local
  namespace: default
spec:
  routes:
  # 1) Normal route with retry enabled
  - name: GET /aura
    condition:
      method: GET
      pathRegex: "^/aura$"
    isRetryable: true     # Linkerd MAY retry on 5xx/network errors
  # 2) Slow route (retry ON to show budget exhaustion)
  - name: GET /slow
    condition:
      method: GET
      pathRegex: "^/slow$"
    isRetryable: true
  # 3) Chaos route (always 500 → retry OFF to avoid retry-storm)
  - name: GET /chaos
    condition:
      method: GET
      pathRegex: "^/chaos$"
    isRetryable: false
  retryBudget:
    retryRatio: 0.2          # extra load ≤ 20 % of originals
    minRetriesPerSecond: 10  # always allow at least 10 r/s
    ttl: 10s                 # budget window length
